spring:
  config:
    import: optional:classpath:.env[.properties]
  .application:
    name: anime Service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimeZone=true&serverTimeZone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy.devdojo: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

database:
  username: ${DB_USERNAME:Arthur}
  password: ${DB_PASSWORD:tuty}
  url: ${DB_URL:localhost}:${DB_PORT:3306}



