spring:
  .application:
    name: anime Service
  threads:
    virtual:
      enabled: true
logging:
  level:
    academy.devdojo: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

database:
  username: ${DB_USERNAME:Arthur}
  password: ${DB_PASSWORD:tuty}
  url: ${DB_URL:localhost}:${DB_PORT:3306}



